#!/bin/bash
#####################################################
# Unix/Linux Folder Tree v2.9                       #
#                                                   #
# Displays structure of folder hierarchy            #
# ------------------------------------------------- #
# This tiny script uses "ls", "grep", and "sed"     #
# in a single command to show the nesting of        #
# subfolders.                                       #
#                                                   #
# Setup:                                            #
#    $ mkdir -p ~/apps/tree                         #
#    Save "tree.sh" into the "~/apps/tree" folder   #
#    $ cd ~/apps/tree                               #
#    $ chmod +x tree.sh                             #
#    $ ln -s tree.sh /usr/local/bin/tree            #
#    $ which tree                                   #
#                                                   #
# Usage:                                            #
#    $ tree [FOLDER]                                #
#                                                   #
# Examples:                                         #
#    $ tree                                         #
#    $ tree /usr/local/etc                          #
#    $ tree ..                                      #
#                                                   #
# WTFPL ~ https://centerkey.com/tree ~ Dem Pilafian #
#####################################################

echo
[ -n "$1" ] && cd "$1"  #if parameter exists, use as base folder
pwd
# command ls -R | sed -e '/:$/!d' -e 's/:$//;s/[^-][^\/]*\//--/g;s/^/   /;s/-/|/'
# 0th sed: select folders
# 1st sed: remove colons
# 2nd sed: replace higher level folder names with dashes
# 3rd sed: indent graph three spaces
# 4th sed: replace first dash with a vertical bar

# command ls -R | sed -e "/^\.\//!d" -e "s/:$//" -e "s/[^\/]*\//--/g" -e "s/^/   |/"
# Transformations:
#     0th sed --> select folders (filter out files)
#     1st sed --> remove trailing colon
#     2nd sed --> replace higher level folder names with dashes
#     3rd sed --> indent graph and add leading vertical bar

command du -h | sed -nE '/\// {h; s/[^─][^\/]*\//──/g; s/─/├/;x;s/([0-9\.MKG]+[\t]+).*/\1/;G; s/\n//}; p'
# 1. For entries with '/'...
#    1. Copy line
#    2. replace higher level folder names with dashes
#    3. replace first dash with a vertical bar
#    4. Exchange result w/original
#    5. Strip text following size & tab(s)
#    6. Append previous reformated line
#    7. Remove
# 2.
topFolders=$(ls -F -1 | grep "/" | wc -l)
test $topFolders -ne 0 || echo "   --> no subfolders"
echo
